import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { ChakraProvider } from '@chakra-ui/react'
import Header from '@/components/Header'
import Nav from '@/components/Nav'
import { Canvas } from "@react-three/fiber";
import { MeshDistortMaterial, Sphere } from "@react-three/drei";
import { About } from '@/components/About'
import Works from '@/components/Works'
// import * as THREE from 'three'

// const  scene = new THREE.Scene();
// const camera = new PerspectiveCamera(70, window.innerWidth / window.innerHeight, 0.1, 1000)
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <ChakraProvider>
      <Head>
        <title>Lizzie's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Header/>
      {/* <Canvas>
        <Sphere visible args={[1, 100, 200]} scale={2}></Sphere>
        <MeshDistortMaterial
	color="#8352FD"
  attach="material"
  distort={0.3}
  speed={1.5}
  roughness={0}
/>
<mesh rotation={[90, 0, 20]}>
	<boxBufferGeometry attach="geometry" args={[3, 3, 3]} />
  <meshLambertMaterial attach="material" color="blue" />
</mesh>
      </Canvas> */}
      
<About/>
<Works/>
    </ChakraProvider>
  )
}
